author = "Abdel Benamrouche, based on Keichi Takahashi's Vienna theme"
description = "Simple and clean blog theme for hugo"
license = "MIT"
name = "hugo-unxp"
source_repo = "https://github.com/abdel-unxp/hugo-theme-unxp.git"
tags = ["blog", "tags", "bootstrap"]
